version: '3.8'

services:
  db:
    image: postgres:13.6-bullseye
    environment:
      POSTGRES_DB: poshtiban
      POSTGRES_USER: poshtiban
      POSTGRES_PASSWORD: poshtiban
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
