version: '3.8'

services:
  moori:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: moori
      DB_USER: moori
      DB_PASSWORD: moori
      DB_ENGINE: django.db.backends.postgresql
      SETTINGS: testing
      SECRET_KEY: "django-insecure-xf787mwonq2s5*i%npk!-tqu8qgsn_g0fe*%vgsrfel7zvr_s1"
    command: test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.6-bullseye
    environment:
      POSTGRES_DB: moori
      POSTGRES_USER: moori
      POSTGRES_PASSWORD: moori
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U moori" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
