# Generated by Django 4.2.8 on 2024-01-18 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.CharField(max_length=24, unique=True)),
                (
                    "code",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("capacity", models.PositiveIntegerField()),
                (
                    "rate",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ]
                    ),
                ),
                ("area_size", models.PositiveIntegerField()),
            ],
        ),
    ]
