# Generated by Django 4.2.8 on 2024-01-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_slots', to='place.place')),
            ],
        ),
    ]
