# Generated by Django 4.2.8 on 2024-01-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_reserveslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveslot',
            old_name='code',
            new_name='place',
        ),
    ]
